name: Deploy to Deno Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: ojjys-game-hub
          entrypoint: server.ts
          exclude: |
            public/bitlife
            public/chess
            public/cookieclicker
            public/coreball
            public/crossyroadspace
            public/driftboss
            public/drifthunters
            public/drivemad
            public/ducklife1
            public/ducklife2
            public/ducklife3
            public/ducklife4
            public/ducklife5
            public/ducklife6
            public/fallguys
            public/geometrydash
            public/geometrydashlite
            public/gettingoverit
            public/gladihoppers
            public/leveldevil
            public/motox3m
            public/ngon
            public/ojjyclient
            public/ovo
            public/retrobowl
            public/rocketgoalio
            public/spacewaves
            public/stickmanhook
            public/subwayssurfersny
